# Generated by Django 4.2.11 on 2024-04-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cartitemmodel_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.SmallIntegerField(default=0)),
                ("quantity", models.SmallIntegerField(default=1)),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="cartitemmodel",
            name="color",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
