# Generated by Django 4.2.11 on 2024-04-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_productcategorymodel_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="avg_rate",
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.ManyToManyField(
                related_name="products", to="shop.productcategorymodel"
            ),
        ),
    ]
