# Generated by Django 4.2.11 on 2024-04-12 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_productcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcomment",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="productcomment",
            old_name="article",
            new_name="product",
        ),
    ]
